version: "3.8"

services:
  actix-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - MALLOC_CONF=dirty_decay_ms:100,muzzy_decay_ms:100
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
        reservations:
          cpus: '1'
          memory: 64M
